[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "APdp1uxa4UKMutUDnKXGJ67ecLaLhvNgDZwUJ4hTpCTC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\jessi\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
